services:
  edubots-server:    
    container_name: client_backend
    build:      
      context: .
      dockerfile: Dockerfile
    expose:
     - 5032    
    environment:
     - CHOKIDAR_USERPOLLING=true     
     - TZ=Africa/Johannesburg
    ports:
     - 5032:3000
    volumes:
     - type: bind
       source: /etc/edubots/server 
       target: api         

  edubots-db:
    image: mysql:8.0.3
    network_mode: bridge
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: edubotslms@123
        MYSQL_DATABASE: EdubotsLMS
    ports:
      - 5507:3306

  edubots-phpmy:
    image: phpmyadmin
    network_mode: bridge
    restart: always
    ports:
      - 5090:80
    environment:
      - PMA_ARBITRARY=1    
