services:
  edubots-client:    
    container_name: client_frontend
    build:            
      context: .
      dockerfile: Dockerfile
    expose:
     - 5031
    ports:
     - 5031:80
    environment:
     - CHOKIDAR_USERPOLLING=true  
